# These are supported funding model platforms

github: # e.g., [user1, user2]
patreon: # your Patreon username
open_collective: # your Open Collective username
ko_fi: # your Ko-fi username
tidelift: # e.g., npm/your-package
community_bridge: # e.g., cloud-foundry
liberapay: zakiulhassan
issuehunt: # your IssueHunt username
lfx_crowdfunding: e27977fc-c17a-4970-9b46-71a65a3d0627
polar: # your Polar username
buy_me_a_coffee: # your Buy Me a Coffee username
thanks_dev: # your thanks.dev username
custom: # e.g., ['https://yoursite.com/donate']
